#!/bin/bash
#
# Perform any post-install operations, e.g. creating SRs
#
# chkconfig: 2345 09 76
# description: Setup eth0 with a static ip for VPX communication with ESX host. # This script will run but gracefully exit on a VPX running on XenServer.

ETH0_FILE='/etc/sysconfig/network-scripts/ifcfg-eth0'

start() {

	if [ ! -e '/usr/bin/vmtoolsd' ]; then
    		#Case of VPX without VMware vmtools installed. Graceful exit.
		echo "vmtoolsd not installed. Exiting gracefully."
    		exit 0
	fi

	echo "VMware vmtools detected. Reading guest information from vmtools."

	KEY_GUESTIP_VALUE=`vmtoolsd --cmd='info-get guestinfo.guestip' &2>/dev/null` || true

	if [ "$KEY_GUESTIP_VALUE" != "" ]
	then
    		echo "Creating ifcfg-eth0"
    		echo "DEVICE=eth0" > $ETH0_FILE
		echo "IPADDR=$KEY_GUESTIP_VALUE" >> $ETH0_FILE
		echo "ONBOOT=yes" >> $ETH0_FILE
		echo "BOOTPROTO=static" >> $ETH0_FILE
		echo "NETMASK=255.255.255.0" >> $ETH0_FILE
		echo "TYPE=Ethernet" >> $ETH0_FILE
		echo "NOZEROCONF=yes" >> $ETH0_FILE
    	fi 
}

case "$1" in
    start)
        start
        ;;
    *)
        echo "Unknown action '$1'."
        ;;
esac

