#!/bin/bash
#
# Perform any post-install operations, e.g. creating SRs
#
# chkconfig: 2345 24 76
# description: Perform post-install operations, e.g. creating SRs

. /etc/init.d/functions

export FIRSTBOOT_SCRIPTS_DIR=/etc/firstboot.d
export FIRSTBOOT_DATA_DIR=/etc/firstboot.d/data
export FIRSTBOOT_STATE_DIR=/etc/firstboot.d/state
export FIRSTBOOT_LOG_DIR=/etc/firstboot.d/log

SCRIPTS="$(find ${FIRSTBOOT_SCRIPTS_DIR} -maxdepth 1 -mindepth 1 -type f -perm -100 | sort)"

## STATE MANAGEMENT
get_statefile_name() {
    echo "${FIRSTBOOT_STATE_DIR}/$(basename $1)"
}

mark_started() {
    echo "started $(date)" >$(get_statefile_name $1)
}

mark_success() {
    echo "success $(date)" >$(get_statefile_name $1)
}

mark_fail() {
    echo "failed $(date)" >$(get_statefile_name $1)
}

mark_new() {
    rm -f $(get_statefile_name $1)
}

get_state() {
    if [ ! -f "$(get_statefile_name $1)" ]; then
        echo "new"
    else
        awk '{print $1;}' $(get_statefile_name $1)
    fi
}

get_logfile_name() {
    echo ${FIRSTBOOT_LOG_DIR}/$(basename $1).log
}

get_runlist() {
    localrl=""
    for s in ${SCRIPTS} ; do
        if [ $(get_state $s) == "new" ]; then
            rl="$rl $(basename $s)"
        fi
    done
    echo $rl
}

start() {
    echo -n $"Performing remaining startup actions: "
    
    # make sure we never do this twice:
    RUNLIST=$(get_runlist)
    if [ -n "${RUNLIST}" ] ; then
        for s in $(get_runlist) ; do
            mark_started ${s}
            if ! bash -x ${FIRSTBOOT_SCRIPTS_DIR}/${s} start &>$(get_logfile_name ${s}) ; then
                problem="Failed: $(basename ${s})"
                mark_fail ${s}
                echo -n ${problem}
                failure ${problem}
                echo
            else
                mark_success ${s}
            fi
        done
    fi

    success
}

status() {
    for s in ${SCRIPTS} ; do
        STATE="$(get_state ${s})"
        echo "$(basename ${s}): ${STATE}"
    done
}

stop() {
    :
}

restart() {
    stop
    start
}

activate() {
    echo -n $"Activating firstboot scripts: "
    for i in ${SCRIPTS} ; do
        mark_new $i
    done
    echo
    success
    /sbin/reboot
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    activate)
        activate
        ;;
    *)
        echo "Unknown action '$1'."
        ;;
esac
